name: deploy
on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 26
        cache: 'npm'
    - name: install dependencies
      run: npm ci
    - name: lint
      run: npm run lint
    - name: type-check
      run: npm run type-check
    - name: build
      run: npm run build
    - name: deploy build
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: burnett01/rsync-deployments@155b6d6c1219ab2224c20c58d423a3f1b850395f # 9.0.1
      with:
        switches: -avr
        path: dist/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
